#ifndef ZZUTIL_ERRMSG_H
#define ZZUTIL_ERRMSG_H

enum ZZECODE {
    ZZECODE_OK = 0,
    ZZECODE_NO_INIT = 1,
    ZZECODE_OS_ERROR = 2,
    ZZECODE_BUFFER_TOO_SMALL = 3,
    ZZECODE_SETSOCKET_FAILED = 4,
    ZZECODE_SKF_ERR = 5,
    ZZECODE_PARAM_ERR = 8,
    ZZECODE_ALREADY_IMPORT = 9,
    ZZECODE_DOUBLE_RELEASE = 11,
    ZZECODE_FILE_ALREADY_EXIST = 12,
    ZZECODE_FILE_NOT_EXIST = 13,
    ZZECODE_FILE_OPEN_FAILED = 14,
    ZZECODE_PIN_INCORRECT = 15,
    ZZECODE_PIN_LOCKED = 16,
    ZZECODE_CRYPT_NO_INIT = 6,
    ZZECODE_CRYPT_ALREADY_INIT = 7,
    ZZECODE_CRYPT_NO_DEVICE = 10,
    ZZECODE_CRYPT_WRONG_LOAD_POSITION = 17,
    ZZECODE_CRYPT_SSL_ERR = 18,
    ZZECODE_CRYPT_BAD_FORMAT = 19,
    ZZECODE_X_ERR = 20,
    ZZECODE_FFMPEG_ERR = 21,
};

#endif // ZZUTIL_ERRMSG_H
