#ifndef ZZUTIL_ERRMSG_H
#define ZZUTIL_ERRMSG_H

#define ZZECODE_OK 0
#define ZZECODE_NO_INIT 1
#define ZZECODE_OS_ERROR 2
#define ZZECODE_BUFFER_TOO_SMALL 3
#define ZZECODE_SETSOCKET_FAILED 4
#define ZZECODE_SKF_ERR 5
#define ZZECODE_CRYPO_NO_INIT 6
#define ZZECODE_CRYPO_ALREADY_INIT 7
#define ZZECODE_PARAM_ERR 8
#define ZZECODE_ALREADY_IMPORT 9

#endif // ZZUTIL_ERRMSG_H
